### ISSUE TITLE
Arithmetic overflow problem

### ISSUE THREAD

**Issue by abse4411** [ybarancan/efficient_spectral_cnn#5]
Hi 
In "[https://github.com/ybarancan/efficient_spectral_cnn/blob/master/tester.py](tester.py) " line 69:
```
        img1 = (255*img1).astype(np.uint8).squeeze()
        img2 = (255*img2).astype(np.uint8).squeeze()
```
Arithmetic operation in unit8 type may occur arithmetic overflow problem.

For example, I run the code below:
```
import numpy as np

a = np.array([1],dtype=np.uint8)
b = np.array([2],dtype=np.uint8)
print("a:",a,a.dtype,"  b:",b,b.dtype)
print("result of a-b:",a-b,(a-b).dtype)

a = np.array([17],dtype=np.uint8)
b = np.array([1],dtype=np.uint8)
print("a:",a,a.dtype,"  b:",b,b.dtype)
print("result of (a-b)**2:",(a-b)**2,((a-b)**2).dtype)
```
It's output:
```
a: [1] uint8   b: [2] uint8
result of a-b: [255] uint8
a: [17] uint8   b: [1] uint8
result of (a-b)**2: [0] uint8
```

So, It will be a bad result when calculating RMSE , rRMSE ... by using the uint8 type:
```
    aae = np.mean(np.sqrt((img1 - img2) ** 2))
    temp = np.mean(np.sqrt((img1 - img2) ** 2)/img2)
```

**Comment by ybarancan** [comment]
Hi,
Yes you are right. After setting it to uint8, it should be converted back to float. The results with float (set unt=False) make much more sense. The uint version was written because of confusion about how the other papers calculated theirs.

**Comment by abse4411** [comment]
> Hi,
> Yes you are right. After setting it to uint8, it should be converted back to float. The results with float (set unt=False) make much more sense. The uint version was written because of confusion about how the other papers calculated theirs.


Why is the test image not multiplied by 255 while unt = False in your code?
I refactor the test code to solve the problem as mentioned above and the error of dividing by zero(for CAVE dataset, which contains zero value in HS images).

```
def tester_psnr(img1, img2, unt):
    print("img1 max : " + str(max(img1.flatten())) + " : mean : " + str(np.mean(img1)))
    print("img2 max : " + str(max(img2.flatten())) + " : mean : " + str(np.mean(img2)))
    scale = 2
    if unt:

        img1 = (255 * img1).astype(np.int32).squeeze()
        img2 = (255 * img2).astype(np.int32).squeeze()
        PIXEL_MAX = 255
    else:
        img1 = (255 * img1).astype(np.float32).squeeze()
        img2 = (255 * img2).astype(np.float32).squeeze()
        PIXEL_MAX = 1
    if len(img1.shape) == 2:
        img1 = img1[scale:-scale, scale:-scale]
        img2 = img2[scale:-scale, scale:-scale]
    else:
        img1 = img1[scale:-scale, scale:-scale, :]
        img2 = img2[scale:-scale, scale:-scale, :]

    img2_mean = np.mean(img2)
    err = img1 - img2
    # Avoid dividing by zero
    if unt:
        img2[img2 < 1] = 1
    else:
        img2[img2 == 0] = 1

    mse = np.mean((err) ** 2)

    t = np.sqrt(mse)

    aae = np.mean(np.sqrt((err) ** 2))
    temp = np.mean(np.sqrt((err) ** 2) / img2)

    return t, t / img2_mean, aae, temp
```

**Comment by ybarancan** [comment]
When the results are calculated using float, i.e. unt = False, max pixel is taken as 1. So we expect the output and ground truth to be normalized [0,1].

**Comment by abse4411** [comment]
> When the results are calculated using float, i.e. unt = False, max pixel is taken as 1. So we expect the output and ground truth to be normalized [0,1].

Ok. I get it. So all the values of RMSE in the paper are calculated using float after being normalized to [0,1], is it right? 🤣I feel puzzled.

**Comment by ybarancan** [comment]
The problem is we wanted to provide fair comparison with all other methods and we weren't sure how they calculated their errors. So at the tester file, you will see each error is printed with its name. We took all of them into consideration and reported. In the paper, there are 6 metrics reported. But the float with [0,1] is the most logical one. So for your comparisons, I would recommend you use that one. For rRMSE vs RMSE, I suggest you take both into consideration since rRMSE is normalized version of RMSE and also makes sense.

**Comment by abse4411** [comment]
Thanks a lot. A normalized version of RMSE is necessary for people.
